/**
 * Characterization tests for colorizeText.
 *
 * These tests lock the exact HTML output of the *current* implementation.
 * Their purpose is NOT to verify that the output is pedagogically "correct" —
 * it is to catch any character-level regression when refactoring colorize.ts.
 *
 * Generated by running colorizeText against each case and recording the result.
 * If the output intentionally changes (bug fix, design decision), update the
 * expected string and leave a comment explaining why.
 */

import { describe, it, expect } from 'vitest';
import { colorizeText } from './colorize';

const C1 = '#0e7490'; // palette doux — color A
const C2 = '#92400e'; // palette doux — color B
const CS = '#b8b0a0'; // SILENT_COLOR

describe('colorizeText — characterization (palette: doux)', () => {
  // ── Empty / whitespace-only input ──────────────────────────────────────────

  it('returns empty string for empty input', () => {
    expect(colorizeText('', 'syllabe', 'doux')).toBe('');
  });

  it('returns empty string for whitespace-only input', () => {
    expect(colorizeText('   ', 'syllabe', 'doux')).toBe('');
  });

  // ── Single word: mode syllabe ──────────────────────────────────────────────

  it('mode syllabe — "chat" is one syllable → one colored span', () => {
    expect(colorizeText('chat', 'syllabe', 'doux')).toBe(
      `<span style="color:${C1}">chat</span>`,
    );
  });

  // ── Single word: mode mot ──────────────────────────────────────────────────

  it('mode mot — "chat" → one colored span', () => {
    expect(colorizeText('chat', 'mot', 'doux')).toBe(
      `<span style="color:${C1}">chat</span>`,
    );
  });

  // ── Single word: mode ligne ────────────────────────────────────────────────

  it('mode ligne — "chat" → colored div', () => {
    expect(colorizeText('chat', 'ligne', 'doux')).toBe(
      `<div style="color:${C1}">chat</div>`,
    );
  });

  // ── Phrase with apostrophe, accented vowels, punctuation ───────────────────

  it('mode syllabe — "L\'école est belle." — apostrophe, accent, trailing dot', () => {
    // "L'" → syllable of "L", counter 0 → C1
    // "école" → one syllable, counter 1 → C2
    // "est" → one syllable, counter 2 → C1
    // "bel" → counter 3 → C2; "le." → counter 4 → C1
    expect(colorizeText("L'école est belle.", 'syllabe', 'doux')).toBe(
      `<span style="color:${C1}">L'</span>` +
      `<span style="color:${C2}">école</span>` +
      `<span> </span>` +
      `<span style="color:${C1}">est</span>` +
      `<span> </span>` +
      `<span style="color:${C2}">bel</span>` +
      `<span style="color:${C1}">le.</span>`,
    );
  });

  it('mode mot — "L\'école est belle." — apostrophe NOT split in mot mode', () => {
    // In mot mode mergeApostropheParts is NOT called; whole "L'école" = 1 word
    expect(colorizeText("L'école est belle.", 'mot', 'doux')).toBe(
      `<span style="color:${C1}">L'école</span>` +
      `<span> </span>` +
      `<span style="color:${C2}">est</span>` +
      `<span> </span>` +
      `<span style="color:${C1}">belle.</span>`,
    );
  });

  // ── Multiline: mode ligne ──────────────────────────────────────────────────

  it('mode ligne — two lines → two colored divs', () => {
    expect(colorizeText('Bonjour\nMonde', 'ligne', 'doux')).toBe(
      `<div style="color:${C1}">Bonjour</div>` +
      `<div style="color:${C2}">Monde</div>`,
    );
  });

  it('mode ligne — empty middle line → &nbsp; div', () => {
    expect(colorizeText('Bonjour\n\nMonde', 'ligne', 'doux')).toBe(
      `<div style="color:${C1}">Bonjour</div>` +
      `<div style="color:${C2}">&nbsp;</div>` +
      `<div style="color:${C1}">Monde</div>`,
    );
  });

  // ── Multiline: mode syllabe — newline becomes <br> ─────────────────────────

  it('mode syllabe — newline becomes <br>, counter continues across lines', () => {
    // Bon(C1) jour(C2) <br> Mon(C1) de... wait:
    // bonjour → bon(C1, count=1) jour(C2, count=2)
    // <br> for \n token
    // monde → monde(C1, count=3) — monde is one piece
    expect(colorizeText('Bonjour\nMonde', 'syllabe', 'doux')).toBe(
      `<span style="color:${C1}">Bon</span>` +
      `<span style="color:${C2}">jour</span>` +
      `<br>` +
      `<span style="color:${C1}">Monde</span>`,
    );
  });

  // ── Number token ───────────────────────────────────────────────────────────

  it('mode syllabe — pure number treated as single color block', () => {
    // "J'" → J(C1,cnt=1) "ai" → ai(C2,cnt=2) " " "3" → 3(C1,cnt=3) " " "chats." → chats.(C2,cnt=4)
    expect(colorizeText("J'ai 3 chats.", 'syllabe', 'doux')).toBe(
      `<span style="color:${C1}">J'</span>` +
      `<span style="color:${C2}">ai</span>` +
      `<span> </span>` +
      `<span style="color:${C1}">3</span>` +
      `<span> </span>` +
      `<span style="color:${C2}">chats.</span>`,
    );
  });

  // ── showSilent: renderWithSilent & run-merging ─────────────────────────────

  it('mode syllabe, showSilent — "chat": final t gets SILENT_COLOR', () => {
    // "chat" is one syllable; final t (index 3) is silent
    // run C1: "cha" | run CS: "t"
    expect(colorizeText('chat', 'syllabe', 'doux', true)).toBe(
      `<span style="color:${C1}">cha</span>` +
      `<span style="color:${CS}">t</span>`,
    );
  });

  it('mode syllabe, showSilent — "pomme": split across 2 syllables + silent final e', () => {
    // pomme → pom(C1) | me(C2)
    // silent indices for "pomme": {4} (final e)
    // pom: offset=0, indices 0,1,2 not silent → single C1 run
    // me: offset=3, index 3(m)=not silent → C2 run "m"; index 4(e)=silent → CS run "e"
    expect(colorizeText('pomme', 'syllabe', 'doux', true)).toBe(
      `<span style="color:${C1}">pom</span>` +
      `<span style="color:${C2}">m</span>` +
      `<span style="color:${CS}">e</span>`,
    );
  });

  // ── HTML escaping ──────────────────────────────────────────────────────────

  it('mode syllabe — HTML special chars are escaped', () => {
    expect(colorizeText('a<b', 'syllabe', 'doux')).toBe(
      `<span style="color:${C1}">a&lt;b</span>`,
    );
  });

  it('mode mot — HTML special chars are escaped', () => {
    expect(colorizeText('a<b', 'mot', 'doux')).toBe(
      `<span style="color:${C1}">a&lt;b</span>`,
    );
  });

  it('mode ligne — HTML special chars are escaped', () => {
    expect(colorizeText('a<b', 'ligne', 'doux')).toBe(
      `<div style="color:${C1}">a&lt;b</div>`,
    );
  });

  // ── Multiple spaces (passthrough preservation) ─────────────────────────────

  it('mode syllabe — multiple spaces preserved as passthrough span', () => {
    expect(colorizeText('a  b', 'syllabe', 'doux')).toBe(
      `<span style="color:${C1}">a</span>` +
      `<span>  </span>` +
      `<span style="color:${C2}">b</span>`,
    );
  });

  it('mode mot — multiple spaces preserved as passthrough span', () => {
    expect(colorizeText('a  b', 'mot', 'doux')).toBe(
      `<span style="color:${C1}">a</span>` +
      `<span>  </span>` +
      `<span style="color:${C2}">b</span>`,
    );
  });
});
